### ISSUE TITLE
Keep up with main branch

### ISSUE THREAD

**Issue by Egoscio** [mhsjlw/mafia-hacked-client#2]
Apparently this fork of Mafia is listed higher on search engines comparing to [the original](https://github.com/annoyingcalc/Mafia-Hacked-Client) for some reason. It is in turn indirectly representing Mafia as a whole, and must ideally be updated with the latest commits so people don't get an outdated copy of the client.

**Comment by mhsjlw** [comment]
Should I just detach it as a fork and give you guys credit and permission to commit? And of course, sync it with the current Mafia Hacked Client?

**Comment by rom1504** [comment]
Why not merging the changes into the original ?

**Comment by mhsjlw** [comment]
I have no idea, I'm just doing as they ask. But, 
> Egoscio: Apparently this fork of Mafia is listed higher on search engines comparing to the original for some reason.

**Comment by mhsjlw** [comment]
You both have been added as collaborators.

**Comment by rom1504** [comment]
@Egoscio @annoyingcalc @mhsjlw you should decide where is the main repo, and PR to it.
And then you should probably put this in npm :)

**Comment by mhsjlw** [comment]
yeah, we need to make it better work first, then that's the plan I believe

**Comment by Egoscio** [comment]
I'm hoping to release binaries as the main distribution type, as most minecrafters aren't willing to go through the installation of node and mafia to get their hands on a simple hacked client (they're spoiled with the common installation process of dragging and dropping the modded jar in their minecraft folder). I'm personally not really worried about what the main repo is, but it does sound a bit silly that right now the most famous one is the fork :P

**Comment by mhsjlw** [comment]
Well, it doesn't matter I can just delete my fork, we've pretty much got the same changes. Maybe give me contributor access on annoyingcalc's repo?
